# Generated by Django 3.2.19 on 2023-06-21 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Condition', models.CharField(default='No Condition Specified', max_length=200)),
                ('Shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20)),
                ('Appointment_type', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('First_name', models.CharField(max_length=100)),
                ('Middle_name', models.CharField(blank=True, max_length=100)),
                ('Last_name', models.CharField(blank=True, max_length=100)),
                ('Date_of_joining', models.DateField()),
                ('Department', models.CharField(max_length=100)),
                ('Phone_number', models.PositiveBigIntegerField(unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('Unique_Id', models.CharField(max_length=15, unique=True)),
                ('First_name', models.CharField(max_length=100)),
                ('Middle_name', models.CharField(blank=True, max_length=100)),
                ('Last_name', models.CharField(blank=True, max_length=100)),
                ('Date_Of_Birth', models.DateField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('Phone', models.PositiveBigIntegerField(unique=True)),
                ('Email', models.EmailField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=500)),
                ('Age', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('Medicine', models.CharField(max_length=200)),
                ('Quantity', models.PositiveIntegerField()),
                ('Expiry_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('Prescribed_medicines', models.TextField(default='No Medicine Prescribed')),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.appointmentlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('Username', models.CharField(max_length=200, unique=True)),
                ('Password', models.CharField(max_length=200)),
                ('isActive', models.BooleanField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointmentlist',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Api.patient'),
        ),
    ]
