# Generated by Django 3.2.19 on 2023-06-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentlist',
            name='Note',
            field=models.TextField(blank=True),
        ),
    ]
