# Generated by Django 4.1.7 on 2023-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Phone_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
