# Generated by Django 4.1.7 on 2023-05-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_employee_phone_number_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Middle_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
