# Generated by Django 3.2.19 on 2023-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_appointmentlist_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlist',
            name='Shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20),
        ),
    ]
