# Generated by Django 3.2.19 on 2023-06-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_appointmentlist_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
    ]
