# Generated by Django 4.1.7 on 2023-05-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_employee_last_name_alter_employee_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
